### PR TITLE
Create Thruster Nodes

### PR DESCRIPTION
**Pull request by Williangalvani**
This makes assembling rovs a little more intuitive, as the position and directions of the thrusters can be better visualized in the editor.

image

This also spits out a motors Matrix:

https://user-images.githubusercontent.com/4013804/105774701-5eedf500-5f44-11eb-9c4d-ad8e3f5b25fd.mp4

### CODE REVIEW

**Comment by patrickelectric** [comment]
Is it possible somehow to display the motor rotation as cw or ccw ?

**Comment by Williangalvani** [comment]
> Is it possible somehow to display the motor rotation as cw or ccw ?

I intend to rave an arc around it for the direction of the propeller and counter-torque eventually, but we don't simulate that yet

**Comment by patrickelectric** [comment]
for reference: https://github.com/bluerobotics/bluesim/issues/43

**Review by patrickelectric — CHANGES_REQUESTED** [review]
From godot:
image

image

Tested with 38abf05f966202e09622824087ab34dcd6946e4e

**Comment by Williangalvani** [comment]
that is odd, did you checkout with godot open? it doesn't like it very much

**Comment by patrickelectric** [comment]
> that is odd, did you checkout with godot open? it doesn't like it very much

It's still failing to load but the first error message does not exist, not sure what exactly happening.

image

image

**Comment by Williangalvani** [comment]
@patrickelectric do you mind trying this again? I can't replicate your issue. Are you on Godot 3.2.3 ?

**Comment by patrickelectric** [comment]
@Williangalvani the file does not exist 
image
image

**Review by patrickelectric — APPROVED** [review]

**Pull request merged**
